---

dist: noble

language: python
python:
  - "3.13"
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] https://apt.releases.hashicorp.com noble main'
        key_url: 'https://apt.releases.hashicorp.com/gpg'
    update: true
    packages:
      - bridge-utils
      - dnsmasq-base
      - ebtables
      - virtinst
      - qemu-kvm
      - qemu-utils
      - libvirt-dev
      - libvirt-daemon-system
      - libguestfs-tools
      - libxslt-dev
      - libxml2-dev
      - zlib1g-dev
      - ruby-dev
      - ruby-fog-libvirt
      - ca-certificates
      - curl
      - gcc
      - iproute2
      - sudo
      - vagrant

install:
  - vagrant plugin install vagrant-libvirt
  - pip install uv
  - sudo chmod o+rwx /var/run/libvirt/libvirt-sock

script:
  - mv ../nfs_server ../tcharl.nfs_server
  - cd ../tcharl.nfs_server
  - uv tool run --python 3.13 --from ansible-core ansible-galaxy role install -r requirements-standalone.yml
  - uv tool run --python 3.13 --from ansible-core ansible-galaxy collection install -r requirements-collections.yml
  - travis_wait 30 uv tool run --python 3.13 --with tox tox -e test-exec -- --scenario-name kvm
branches:
  only:
    - master
