---
namespace: "tcharl"
name: "nfs_server"
version: "1.0.1"
description: "Expose an NFS mountpoint protected by freeipa kerberos"

authors:
  - "Charlie Mordant <cmordant1@gmail.com>"

repository: "https://github.com/OsgiliathEnterprise/nfs_server"
documentation: "https://github.com/OsgiliathEnterprise/nfs_server/blob/master/README.md"
homepage: "https://github.com/OsgiliathEnterprise/nfs_server"
issues: "https://github.com/OsgiliathEnterprise/nfs_server/issues"

readme: "README.md"
license:
  - "Apache-2.0"
tags:
  - "freeipa"
  - "nfs"
  - "nfs-server"
