---

- name: Prereq | get current hostname
  ansible.builtin.command: "hostname"
  register: nfs_server_current_machine_hostname
  changed_when: false

- name: Facts | compute idm hostname
  ansible.builtin.set_fact:
    nfs_server_host: "{{ hostname | default(nfs_server_current_machine_hostname.stdout if nfs_server_current_machine_hostname.stdout.endswith(company_domain) else idm_client_default_domain_prefix + '.' + company_domain) }}"

- name: Facts | compute idm hostname
  ansible.builtin.debug:
    msg: "{{ nfs_server_host }}"
    verbosity: 1

- name: Facts | Cat
  ansible.builtin.command:
    cmd: df -h
  changed_when: false
  register: fs_server_df_result
  become: true

- name: Facts | cat mountpoints
  ansible.builtin.debug:
    msg: "{{ fs_server_df_result }}"
    verbosity: 2
