---
# tasks file for ansible-users

- name: Requirements
  ansible.builtin.import_tasks: requirements.yml

- name: Prereq
  ansible.builtin.import_tasks: prereq.yml

- name: Facts
  ansible.builtin.import_tasks: facts.yml

- name: Debug nfs server query
  ansible.builtin.debug:
    msg: "{{ query('subelements', lvm_groups, 'lvmetanames', {'skip_missing':True}) | json_query('[?expose_nfs==True]') | list }}"


- name: Network file system server
  ansible.builtin.include_tasks: nfs-server.yml
  when:
    - lvm_groups is defined
    - query('subelements', lvm_groups, 'lvmetanames', {'skip_missing':True}) | json_query('[?expose_nfs==True]') | length > 0
    - configure_nfs is defined
    - configure_nfs
