---
# tasks file for ansible-users

- name: Requirements
  ansible.builtin.import_tasks: requirements.yml
  when:
    - standalone_role

- name: Prereq
  ansible.builtin.import_tasks: prereq.yml

- name: Facts
  ansible.builtin.import_tasks: facts.yml

- name: Network file system server
  ansible.builtin.include_tasks: nfs-server.yml
  when:
    - lvm_groups is defined
    - q('subelements', lvm_groups, 'lvmetanames', { 'skip_missing': True }) | selectattr('expose_nfs', 'defined') | selectattr('expose_nfs', 'equalto', True) | length > 0
    - configure_nfs is defined
    - configure_nfs
