---
- name: Nfs-entry | ensure mountpoint exists
  ansible.builtin.file:
    path: "{{ lvm.mntp }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  failed_when: False
  become: True

- name: Nfs-entry | add secured mountpoint in export file
  ansible.builtin.lineinfile:
    path: /etc/exports
    regexp: '^{{ lvm.mntp }}'
    insertbefore: BOF
    line: "{{ lvm.mntp }} *(rw,sec=krb5:krb5i:krb5p)"
    owner: root
    group: root
    mode: '0644'
  become: True
  when: lvm.insecure is not defined or not lvm.insecure
  notify: nfs_server | handler | reload-nfsd

- name: Nfs-entry | add insecured mountpoint in export file
  ansible.builtin.lineinfile:
    path: /etc/exports
    regexp: '^{{ lvm.mntp }}'
    insertbefore: BOF
    line: "{{ lvm.mntp }} {{ lvm.min_ip_to_share | ansible.utils.ipsubnet(range_ip_to_share) }}(rw)"
    owner: root
    group: root
    mode: '0644'
  become: True
  when:
   - lvm.insecure is defined
   - lvm.insecure | bool
  notify: nfs_server | handler | reload-nfsd
