---
- name: Nfs-entry | ensure mountpoint exists
  ansible.builtin.file:
    path: "{{ lvm.mntp }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  failed_when: False
  become: True

- name: Nfs-entry | add mountpoint in export file
  ansible.builtin.lineinfile:
    path: /etc/exports
    regexp: '^{{ lvm.mntp }}'
    insertbefore: BOF
    line: '{{ lvm.mntp }} *(rw,sec=krb5:krb5i:krb5p)'
    owner: root
    group: root
    mode: '0644'
  become: True
  changed_when: False