---

- name: Requirements | install volumes
  ansible.builtin.import_role:
    name: tcharl.ansible_volumes

- name: Requirements | install freeipa and declare dns
  ansible.builtin.import_role:
    name: tcharl.ansible_nameserver
