---
- name: Expose NFS
  hosts: datastore.osgiliath.test
  vars:
    secure_logs: false
    company_domain: osgiliath.test
    preferred_nic: "eth1"
    lvm_groups:
      - vgname: non-persistent
        disks:
          - /dev/sdb1
        create: true
        lvmetanames:
          - lvname: nfs_exposed
            size: 4M
            create: true
            filesystem: xfs
            expose_nfs: True
            mntp: /var/nfs
            mount: true
    manage_lvm: true
    configure_nfs: True
  roles:
    - role: tcharl.nfs_server

- name: Consume NFS
  hosts: consumer.osgiliath.test
  vars:
    preferred_nic: "eth1"
    company_domain: osgiliath.test
    configure_nfs: True
    nfs_mountpoints:
      - host: datastore.osgiliath.test
        mountpoints:
         - remote: /var/nfs
           local: /net
  roles:
    - role: tcharl.nfs_client
