---
- name: prepare IPA
  hosts: all
  tasks:
    - name: "install fedora ansible prerequisites"
      ansible.builtin.raw: dnf install -y python3 python3-libdnf5
      changed_when: false
      become: true
    - include_role:
        name: tcharl.nfs_server
        tasks_from: requirements.yml
      vars:
        preferred_nic: "eth1"
        firewalld_zone: "public"
        standalone_role: True
        company_domain: "osgiliath.test" # That server's hostname will be should ipa."{{ company_domain }}"
        company_realm_password: '123ADMin'
        company_ad_password: '123ADmPass'
