---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    roles-path: ${MOLECULE_PROJECT_DIRECTORY}/../community
    requirements-file: requirements-collections.yml
    collections-path: ${MOLECULE_PROJECT_DIRECTORY}/../community-collections
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: datastore.osgiliath.test
    box: fedora/38-cloud-base
    provider_options:
      driver: "kvm"
      cpus: 2
      memory: 2048
    interfaces:
      - auto_config: true
        network_name: private_network
        ip: "192.168.50.5"
    groups:
      - ipaservers
      - ipaclients
    provider_raw_config_args:
      - "storage :file, :size => '1G', :device => 'vdb'"
provisioner:
  name: ansible
#  config_options:
#    defaults:
#      forks: 20
#   ssh_connection:
#     pipelining: true
#      ssh_args: -o ControlMaster=auto -o ControlPersist=6000s
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
scenario:
  name: kvm
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
#    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy