---
- name: Expose NFS
  hosts: all
  vars:
    secure_logs: False
    company_domain: osgiliath.test
    hostname: datastore.osgiliath.test
    preferred_nic: "eth1"
    company_realm_password: '123ADMin'
    company_ad_password: '123ADmPass'
    standalone_role: False
    lvm_groups:
      - vgname: non-persistent
        disks:
          - /dev/sdb
        create: true
        lvmetanames:
          - lvname: nfs_exposed
            size: 4M
            create: true
            filesystem: xfs
            expose_nfs: True
            mntp: /var/nfs
            mount: true
    manage_lvm: true
    configure_nfs: True
  roles:
    - role: tcharl.nfs_server
