---
- name: Expose NFS
  hosts: datastore.osgiliath.test
  vars:
    company_domain: osgiliath.test
    lvm_groups:
      - vgname: non-persistent
        disks:
          - /dev/sdb
        create: true
        lvmetanames:
          - lvname: nfs_exposed
            size: 4M
            create: true
            filesystem: xfs
            expose_nfs: True
            mntp: /var/nfs
            mount: true
    manage_lvm: true
    configure_nfs: True
  roles:
    - role: tcharl.nfs_server
