---
dependency:
  name: galaxy
  enabled: ${DEPENDENCY_ENABLED:-True}
  options:
    role-file: ${REQUIREMENTS_PATH:-requirements-standalone.yml}
    requirements-file: requirements-collections.yml
driver:
  name: vagrant
  provider:
    name: parallels
platforms:
  - name: idm.osgiliath.test
    box: ${TESTBOX:-bento/fedora-43}
    provider_options:
      cpus: 2
      memory: 2048
    interfaces:
      - type: dhcp
        auto_config: true
        network_name: private_network
    groups:
      - ipaservers
  - name: datastore.osgiliath.test
    box: ${TESTBOX:-bento/fedora-43}
    provider_options:
      cpus: 2
      memory: 2048
    interfaces:
      - type: dhcp
        auto_config: true
        network_name: private_network
    groups:
      - ipaclients
    provider_raw_config_args:
      - "customize ['set', :id, '--device-add', 'hdd', '--size', '840']"
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: "${MOLECULE_PROJECT_DIRECTORY}/../community-collections:${HOME}/.ansible/collections:/usr/share/ansible/collections"
    ANSIBLE_VERBOSITY: 2
  config_options:
    defaults:
      remote_tmp: /tmp
#  config_options:
#    defaults:
#      forks: 20
    ssh_connection:
     pipelining: true
     ssh_args: -4 -o ControlMaster=auto -o ControlPersist=6000s
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
scenario:
  name: parallels
