---
dependency:
  name: galaxy
  enabled: ${DEPENDENCY_ENABLED:-True}
  options:
    role-file: ${REQUIREMENTS_PATH:-requirements-standalone.yml}
    roles-path: ${MOLECULE_PROJECT_DIRECTORY}/../community
    requirements-file: requirements-collections.yml
    collections-path: ${MOLECULE_PROJECT_DIRECTORY}/../community-collections
driver:
  name: vagrant
  provider:
    name: parallels
platforms:
  - name: datastore.osgiliath.test
    box: tcharl/fedora-36-aarch64
    provider_options:
      cpus: 2
      memory: 2048
    interfaces:
      - type: dhcp
        auto_config: true
        network_name: private_network
    groups:
      - ipaservers
      - ipaclients
    provider_raw_config_args:
      - "customize ['set', :id, '--device-add', 'hdd', '--size', '840']"
provisioner:
  name: ansible
#  config_options:
#    defaults:
#      forks: 20
#   ssh_connection:
#     pipelining: true
#      ssh_args: -o ControlMaster=auto -o ControlPersist=6000s
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
scenario:
  name: parallels
