---
# This is a basic workflow to help you get started with Actions
name: Molecule

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
    branches:
      - master
      - tags/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: tcharl.nfs_server
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        run: python -m pip install --upgrade uv
      - name: install prereq
        run: |
          cd tcharl.nfs_server
          uv tool run --python 3.13 --from ansible-core ansible-galaxy role install -r requirements-standalone.yml
          uv tool run --python 3.13 --from ansible-core ansible-galaxy collection install -r requirements-collections.yml
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: tcharl.nfs_server
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        run: python -m pip install --upgrade uv
      - name: tox lint
        run: |
          cd tcharl.nfs_server
          uv tool run --python 3.13 --with tox tox -e lint
